package com.iam.core.config;

import com.iam.core.domain.constant.AttributeConstants;
import com.iam.core.domain.constant.ScimConstants;
import com.iam.core.domain.constant.SyncConstants;
import com.iam.core.domain.constant.SystemConstants;
import com.iam.core.domain.entity.EnterpriseUserExtension;
import com.iam.core.domain.entity.IamUser;
import com.iam.core.domain.entity.IamUserExtension;
import com.iam.core.domain.repository.IamUserRepository;
import com.iam.core.domain.repository.SyncHistoryRepository;
import com.iam.core.domain.entity.*;
import com.iam.core.application.service.TransMappingService;
import io.hypersistence.tsid.TSID;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.boot.CommandLineRunner;
import org.springframework.context.annotation.Profile;
import org.springframework.stereotype.Component;
import org.springframework.transaction.annotation.Transactional;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.HashMap;
import java.util.List;
import java.util.Map;

/**
 * 로컬 개발 환경용 초기 데이터 이니셜라이저.
 * iam-ui의 mocks/data.ts와 동일한 데이터를 생성합니다.
 */
@Slf4j
@Component
@RequiredArgsConstructor
@Profile({ "local", "dev", "test", "default" }) // 운영 환경에서는 실행되지 않도록 제한
public class DataInitializer implements CommandLineRunner {

  private final IamUserRepository iamUserRepository;
  private final SyncHistoryRepository syncHistoryRepository;
  private final TransMappingService transMappingService;

  @Override
  @Transactional
  public void run(String... args) throws Exception {
    // Rule Engine Data (Always try to init if mappings are missing)
    initRuleEngineData();

    if (iamUserRepository.count() > 0) {
      log.info("ℹ️ DB에 이미 사용자 데이터가 존재하여 사용자 초기화를 건너뜜...");
      return;
    }

    log.info("🚀 [DataInitializer] 샘플 데이터 생성을 시작합니다...");

    List<IamUser> users = new ArrayList<>();

    // User 1: Super Admin
    users.add(createUser(
        "super.admin", "Michael", "Admin", "IT Director", true, "michael.admin@global-iam.com",
        "GLOBAL-IT", "ADM001", null));

    // User 2: Jane Doe (Auditor)
    IamUser jane = createUser(
        "jane.doe", "Jane", "Doe", "External Auditor", true, "jane.doe@audit-firm.com",
        "AUDIT-01", "EXT-101", null);
    users.add(jane);

    // User 3: John Smith (Security)
    users.add(createUser(
        "john.smith", "John", "Smith", "Security Analyst", true, "john.smith@global-iam.com",
        "SEC-OPS", "SEC-888", null));

    // User 4: Sarah Vendor (Contractor)
    users.add(createUser(
        "sarah.v", "Sarah", "Vendor", "Implementation Partner", false, "sarah.v@partner.com",
        "EXTERNAL-V", "VND-444", null));

    iamUserRepository.saveAll(users);
    log.info("✅ [DataInitializer] 총 {}건의 사용자 데이터를 생성했습니다.", users.size());

    // Sync History Data
    createSyncHistory(jane);
  }

  private void initRuleEngineData() {
    if (transMappingService.countRuleMeta() > 0)
      return;

    log.info("🚀 [DataInitializer] 규칙 엔진 초기 데이터 생성을 시작합니다...");

    String ruleId = "SAP_CORE_TRANS";
    transMappingService.saveRuleMeta(TransRuleMeta.builder()
        .ruleId(ruleId)
        .ruleName("SAP HR Core Transformation")
        .targetAttribute("CORE")
        .status("ACTIVE")
        .build());

    // NOTE: We don't manually create TransRuleVersion here anymore.
    // It will be automatically generated by
    // TransMappingService.saveMapping(fieldMapping)
    // which triggers RuleScriptGenerator.

    transMappingService.saveTransMapping(TransMapping.builder()
        .systemId(SystemConstants.SYSTEM_SAP_HR)
        .ruleId(ruleId)
        .execOrder(1)
        .isMandatory(true)
        .build());

    // Initial Field Mappings
    createCodeMappings();
    createFieldMappings(ruleId);

    log.info("✅ [DataInitializer] {} 규칙 매핑을 생성했습니다.", SystemConstants.SYSTEM_SAP_HR);
  }

  private void createCodeMappings() {
    String groupId = "RANK_CODE";
    transMappingService.saveCodeMeta(TransCodeMeta.builder()
        .codeGroupId(groupId)
        .description("Rank Code Mapping (HR -> IAM)")
        .build());

    transMappingService.saveCodeValues(List.of(
        TransCodeValue.builder().codeGroupId(groupId).sourceValue("A").targetValue("1").label("사원").build(),
        TransCodeValue.builder().codeGroupId(groupId).sourceValue("B").targetValue("2").label("대리").build(),
        TransCodeValue.builder().codeGroupId(groupId).sourceValue("C").targetValue("3").label("과장").build()));
  }

  private void createFieldMappings(String ruleId) {
    List<TransFieldMapping> mappings = List.of(
        // 1. Core Attributes (IamUser fields)
        TransFieldMapping.builder().ruleId(ruleId).sourceField("email").targetField("userName").isRequired(true)
            .build(),
        TransFieldMapping.builder().ruleId(ruleId).sourceField("lastName").targetField("familyName").build(),
        TransFieldMapping.builder().ruleId(ruleId).sourceField("firstName").targetField("givenName").build(),
        TransFieldMapping.builder().ruleId(ruleId).sourceField("position").targetField("title").build(),

        // 2. Active Status (Custom logic to handle "ACTIVE" -> true)
        TransFieldMapping.builder().ruleId(ruleId).sourceField("status").targetField("active")
            .transformType("CUSTOM")
            .transformScript("new com.iam.core.domain.vo.BooleanData(source.status?.asString() == 'ACTIVE')")
            .build(),

        // 3. Extension Attributes (EnterpriseUserExtension)
        TransFieldMapping.builder().ruleId(ruleId).sourceField("empNo").targetField("employeeNumber").isRequired(true)
            .build(),
        TransFieldMapping.builder().ruleId(ruleId).sourceField("deptCode").targetField("department").build());

    // Use the service to trigger script generation
    mappings.forEach(transMappingService::saveMapping);
  }

  private void createSyncHistory(IamUser user) {
    try {
      List<com.iam.core.domain.entity.SyncHistory> histories = new ArrayList<>();
      String traceId = "T-" + TSID.fast().toLong();
      Long userId = user.getId();
      String userName = user.getUserName();

      // Extract details from User object for consistency
      String firstName = user.getGivenName();
      String lastName = user.getFamilyName();
      String email = userName;
      String title = user.getTitle();

      // Extract extension data safely
      String empNo = "UNKNOWN";
      String dept = "UNKNOWN";
      if (user.getExtension() != null
          && user.getExtension().getExtensions().containsKey(ScimConstants.URN_ENTERPRISE_USER)) {
        EnterpriseUserExtension ext = (EnterpriseUserExtension) user.getExtension().getExtensions()
            .get(ScimConstants.URN_ENTERPRISE_USER);
        empNo = ext.getEmployeeNumber();
        dept = ext.getDepartment();
      }

      // Sample Raw Data from HR (Simulated based on User)
      Map<String, Object> hrRawData = new HashMap<>();
      hrRawData.put("empNo", empNo);
      hrRawData.put("firstName", firstName);
      hrRawData.put("lastName", lastName);
      hrRawData.put("position", title);
      hrRawData.put("deptCode", dept);
      hrRawData.put("email", email);
      hrRawData.put("status", "ACTIVE");
      hrRawData.put("externalId", empNo);

      // 1. HR Sync (User Created from HR)
      // Mirroring UserSyncService.createNewUser logic
      List<Map<String, Object>> mappings = new ArrayList<>();
      mappings.add(createMapping("HR", "IAM", "lastName", "familyName", lastName));
      mappings.add(createMapping("HR", "IAM", "firstName", "givenName", firstName));
      mappings.add(createMapping("HR", "IAM", "email", "userName", email));
      mappings.add(createMapping("HR", "IAM", "position", "title", title));
      mappings.add(createMapping("HR", "IAM", "empNo", "employeeNumber", empNo));
      mappings.add(createMapping("HR", "IAM", "deptCode", "department", dept));
      mappings.add(createMapping("HR", "IAM", "status", "active", "true"));

      // fix map key structure
      Map<String, Object> requestPayloadMap = new HashMap<>(hrRawData);

      Map<String, Object> resultSnapshot = new HashMap<>();
      // In real scenario, resultData would be the transformed user props or changes
      resultSnapshot.put(AttributeConstants.LAYER, "IAM_CORE");
      resultSnapshot.put("user_id", userId);
      resultSnapshot.put("username", userName);

      histories
          .add(createHistory(traceId, SyncConstants.EVENT_USER_CREATE, SyncConstants.STATUS_SUCCESS, userId, userName,
              "SAP_HR", SystemConstants.SYSTEM_IAM, "User created via engine",
              resultSnapshot, requestPayloadMap,
              LocalDateTime.now().minusDays(1)));

      // 2. AD Provisioning
      Map<String, Object> adCmdPayload = new HashMap<>();
      adCmdPayload.put(AttributeConstants.SYNC_TYPE, SyncConstants.TYPE_JOIN);
      adCmdPayload.put("command", "PROVISION");
      adCmdPayload.put("target", "AD");
      adCmdPayload.put("data", Map.of("sAMAccountName", userName, "displayName", firstName + " " + lastName));

      histories
          .add(createHistory(traceId, SyncConstants.EVENT_AD_PROVISION, SyncConstants.STATUS_SUCCESS, userId, userName,
              SystemConstants.SYSTEM_IAM, SystemConstants.SYSTEM_AD, "Provisioned to AD",
              adCmdPayload, null,
              LocalDateTime.now().minusDays(1).plusMinutes(1)));

      syncHistoryRepository.saveAll(histories);
      log.info("✅ [DataInitializer] Refactored SyncHistory data created for {}", userName);

    } catch (Exception e) {
      log.error("Failed to create sync history", e);
    }
  }

  private Map<String, Object> createMapping(String fromLabel, String toLabel, String srcField, String targetField,
      String val) {
    return Map.of(
        AttributeConstants.FROM_LABEL, fromLabel,
        AttributeConstants.TO_LABEL, toLabel,
        AttributeConstants.FROM_FIELD, srcField,
        AttributeConstants.TO_FIELD, targetField,
        AttributeConstants.VALUE, val);
  }

  private com.iam.core.domain.entity.SyncHistory createHistory(String traceId, String type, String status,
      Long iamUserId, String target, String sourceSystem, String targetSystem, String msg,
      Map<String, Object> resultData, Map<String, Object> requestPayload,
      LocalDateTime time) {
    return com.iam.core.domain.entity.SyncHistory.builder()
        .traceId(traceId)
        .type(type)
        .status(status)
        .iamUserId(iamUserId)
        .targetUser(target)
        .sourceSystem(sourceSystem)
        .targetSystem(targetSystem)
        .requestPayload(requestPayload)
        .resultData(resultData)
        .message(msg)
        .createdAt(time)
        .build();
  }

  private IamUser createUser(String userName, String familyName, String givenName,
      String title, boolean active, String email,
      String dept, String empNo, String costCenter) {

    IamUser user = new IamUser();
    user.setUserName(userName);
    user.setFamilyName(familyName);
    user.setGivenName(givenName);
    user.setFormattedName(givenName + " " + familyName);
    user.setTitle(title);
    user.setActive(active);
    user.setCreated(LocalDateTime.now());
    user.setLastModified(LocalDateTime.now());

    // Extension Setup
    IamUserExtension extension = new IamUserExtension();
    extension.setUser(user);

    // Required Schemas
    List<String> schemas = new ArrayList<>();
    schemas.add(ScimConstants.URN_CORE_USER);

    // Enterprise Extension
    EnterpriseUserExtension enterpriseExt = new EnterpriseUserExtension();
    enterpriseExt.setDepartment(dept);
    enterpriseExt.setEmployeeNumber(empNo);
    enterpriseExt.setCostCenter(costCenter);

    extension.getExtensions().put(ScimConstants.URN_ENTERPRISE_USER,
        enterpriseExt);
    schemas.add(ScimConstants.URN_ENTERPRISE_USER);

    extension.setSchemas(schemas);
    user.setExtension(extension);

    return user;
  }
}
