services:
  iam-ui:
    build:
      context: ./iam-ui
      dockerfile: Dockerfile
    image: iam-ui:latest
    container_name: iam-ui
    ports:
      - "15173:80"
    networks:
      - iam-network
    environment:
      - VITE_API_URL=http://iam-registry:18081

  iam-eureka:
    build:
      context: .
      dockerfile: iam-eureka/Dockerfile
    image: iam-eureka:latest
    container_name: iam-eureka
    ports:
      - "8761:8761"
    networks:
      - iam-network

  iam-registry:
    build:
      context: .
      dockerfile: iam-registry/Dockerfile
    image: iam-registry:latest
    container_name: iam-registry
    ports:
      - "18081:18081"
    depends_on:
      - postgres
      - iam-eureka
      - rabbitmq
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/iam_db
      - SPRING_DATASOURCE_USERNAME=iam_user
      - SPRING_DATASOURCE_PASSWORD=iam_password
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://iam-eureka:8761/eureka/
    networks:
      - iam-network

  iam-engine:
    build:
      context: .
      dockerfile: iam-engine/Dockerfile
    image: iam-engine:latest
    container_name: iam-engine
    ports:
      - "18085:8080"
    depends_on:
      - rabbitmq
      - iam-eureka
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://iam-eureka:8761/eureka/
    networks:
      - iam-network

  iam-adapter-db:
    build:
      context: .
      dockerfile: iam-adapter-db/Dockerfile
    image: iam-adapter-db:latest
    container_name: iam-adapter-db
    ports:
      - "18086:8080"
    depends_on:
      - rabbitmq
      - iam-eureka
    environment:
      - SPRING_RABBITMQ_HOST=rabbitmq
      - EUREKA_CLIENT_SERVICEURL_DEFAULTZONE=http://iam-eureka:8761/eureka/
    networks:
      - iam-network

  postgres:
    image: postgres:17-trixie
    container_name: postgres
    environment:
      - POSTGRES_USER=iam_user
      - POSTGRES_PASSWORD=iam_password
      - POSTGRES_DB=iam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iam-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - iam-network

volumes:
  postgres_data:


networks:
  iam-network:
    driver: bridge
