services:
  postgres:
    image: postgres:17-trixie
    container_name: postgres
    environment:
      - POSTGRES_USER=iam_user
      - POSTGRES_PASSWORD=iam_password
      - POSTGRES_DB=iam_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - iam-network

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - iam-network

volumes:
  postgres_data:


networks:
  iam-network:
    driver: bridge
