package com.iam.adapter.db.interfaces.messaging;

import com.iam.adapter.db.application.DynamicDbService;
import lombok.RequiredArgsConstructor;
import lombok.extern.slf4j.Slf4j;
import org.springframework.amqp.rabbit.annotation.Queue;
import org.springframework.amqp.rabbit.annotation.RabbitListener;
import org.springframework.stereotype.Component;

import java.util.Map;

@Slf4j
@Component
@RequiredArgsConstructor
public class OutboundDataListener {

    private final DynamicDbService dynamicDbService;

    @RabbitListener(queuesToDeclare = @Queue("TARGET_OUTBOUND_DATA"))
    public void onTargetDataReceived(Map<String, Object> payload) {
        log.info("Adapter received outbound converted data for target DB: {}", payload);

        // TODO: The payload should contain connection info metadata + values to
        // insert/update, generated by the Engine
        // This acts as a pure delivery mechanism without knowing transformation rules.
        // Example dynamic extraction:
        // String url = (String) payload.get("__target_url");
        // String query = (String) payload.get("__target_query");
        // dynamicDbService.executeUpdate(driver, url, username, password, query,
        // params...);
    }
}
